spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: mseurekauser
      password: senhaeureka

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
